### ISSUE TITLE
First letter of some last words of lines seems sometimes to be duplicated

### ISSUE THREAD

**Issue by wbombardellis** [bombardellif/acrostics-generator#1]
See the word "Institute" of the second line of final text.

How to reproduce:
On head version, read the file "Text/DonaldKnuth", try acrostic "knuth".
Use operators LineBreak and Wrong Hyphenization.

ORIGINAL TEXT:
Knuth ist der Sohn eines Lehrers. Er besuchte die Milwaukee Lutheran
High School und begann sein Physikstudium am California Institute of
Technology im September 1956. Aus zweierlei Gründen schlug er
tatsächlich seinem zweiten Studienjahr jedoch den Weg zur Mathematik
ein: Zum einen löste er ein Problem eines seiner
Mathematikprofessoren, was ihm eine 1,0 als Note einbrachte, zum
anderen fand er wenig Gefallen an den physikalischen Praktika. Er
erhielt einen Bachelor- und einen Master-Abschluss 1960 an der Case
Western Reserve University. 1963 erhielt er seinen Ph.D. vom
California Institute of Technology bei Marshall Hall, wo er dann auch
nach der Promotion Assistant Professor und 1966 Associate Professor
und schließlich Professor wurde. 1968 wurde er Professor für
Informatik an der Stanford University. Ab 1977 war er dort Fletcher
Jones Professor of Computer Science und ab 1990 Professor of the Art
of Computer Programming. Seit 1993 ist er Professor Emeritus.

The Algorithm Result:

Knuth ist der Sohn eines Lehrers. Er besuchte die Milwaukee Luthera-
n High School und begann sein Physikstudium am California IInstit-
ute of Technology im September 1956. Aus zweierlei Gründen schlug er
tatsächlich seinem zweiten Studienjahr jedoch den Weg zur Mat-
hematik ein: Zum einen löste er ein Problem eines s- einer
Mathematikprofessoren, was ihm eine 1,0 als Note einbrachte, zum
anderen fand er wenig Gefallen an den physikalischen Praktika. Er
erhielt einen Bachelor- und einen Master-Abschluss 1960 an der Case
Western Reserve University. 1963 erhielt er seinen Ph.D. vom
California Institute of Technology bei Marshall Hall, wo er dann auch
nach der Promotion Assistant Professor und 1966 Associate Professor
und schließlich Professor wurde. 1968 wurde er Professor für
Informatik an der Stanford University. Ab 1977 war er dort Fletcher
Jones Professor of Computer Science und ab 1990 Professor of the Art
of Computer Programming. Seit 1993 ist er Professor Emeritus.

**Comment by bombardellif** [comment]
Fixed
