### ISSUE TITLE
Exception on Line Break Operation

### ISSUE THREAD

**Issue by wbombardellis** [bombardellif/acrostics-generator#14]
How to reproduce: Text: "Text/William/6.txt" and acrostic "Was". Last version of program. All operators.

ORIGINAL TEXT:
Was Jasmin verschweigt. Mogelbeere. Noch um1800 gehörte der
Mogelbeerbaum zu den häufigsten Baumarten dersüdlichen Länder. Die
Mogelbeere (als unreife Frucht) wurdevon den weiblichen Bewohnern
Italiens, Jugoslawiens, Spaniensund Südfrankreichs lange Zeit als
orales Verhütungsmittelbenutzt. Die getrocknete, etwa pillengroße
Beere garantierte beiregelmäßiger Einnahme nach (nicht vor!) dem
täglichenMorgenstuhlgang dauerhafte Verhinderung einer
Empfängnis.Optimator-Priester aus München führten bei einer
Wallfahrtdie Mogelbeere aus Italien nach Deutschland ein.
Zunächstprofitierten ausnahmslos alle Nonnenklöster deutscher
Bistümervon der Beere; erst nach ca. 70 Jahren fand auch das
deutscheBürgertum zu der Mogelbeere (vermutlich über einige
ausgedienteNonnen).

Progress!!
Was Jasmin verschweigt. Mogelbeere. Noch um1800 gehörte der
Mogelbeerbaum zu den häufigsten Baumarten dersüdlichen Länder. Die
Mogelbeere (als unreife Frucht) wurdevon den weiblichen Bewohnern
Italiens, Jugoslawiens, Spaniensund Südfrankreichs lange Zeit als
orales Verhütungsmittelbenutzt. Die getrocknete, etwa pillengroße
Beere garantierte beiregelmäßiger Einnahme nach (nicht vor!) dem
täglichenMorgenstuhlgang dauerhafte Verhinderung einer
Empfängnis.Optimator-Priester aus München führten bei einer
Wallfahrtdie Mogelbeere aus Italien nach Deutschland ein.
Zunächstprofitierten ausnahmslos alle Nonnenklöster deutscher
Bistümervon der Beere; erst nach ca. 70 Jahren fand auch das
deutscheBürgertum zu der Mogelbeere (vermutlich über einige
ausgedienteNonnen).

Exception in thread "main" java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at controller.Operation.StringToText(Operation.java:57)
	at controller.LineBreakOperation.execute(LineBreakOperation.java:203)
	at model.Algorithm.execute(Algorithm.java:127)
	at controller.Main.main(Main.java:48)
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)

**Comment by juergen123** [comment]
Example Text/William/6.txt now runs without error on 
acrostic "Was". 
Computation in stopped by Timeout
