### ISSUE TITLE
Index Out of Bound Exception with Goethe Text

### ISSUE THREAD

**Issue by wbombardellis** [bombardellif/acrostics-generator#4]
How to reproduce:
On head version, read the file "Text/Goethe", try acrostic "w".
Use operators LineBreak and Wrong Hyphenization.

ORIGINAL TEXT

Johann Wolfgang von Goethe wurde am 28. August 1749 im heutigen Goethe-Haus am Frankfurter Großen Hirschgraben geboren. Der Vater Johann Caspar Goethe (1710–1782), der die ursprüngliche Schreibung des Familiennamens von Göthe in Goethe änderte, war promovierter Jurist, übte diesen Beruf jedoch nicht aus, sondern lebte von den Erträgen seines ererbten Vermögens, das später auch dem Sohn ein Leben ohne finanzielle Zwänge ermöglichen sollte. Er war vielseitig interessiert und gebildet, jedoch auch streng und pedantisch, was wiederholt zu Konflikten in der Familie führte.

Johann Wolfgang von Goethe wurde am 28. August 1749 im heutigen
Goethe-Haus am Frankfurter Großen Hirschgraben geboren. Der Vater
Johann Caspar Goethe (1710–1782), der die ursprüngliche Schreibung des
Familiennamens von Göthe in Goethe änderte, war promovierter Jurist,
übte diesen Beruf jedoch nicht aus, sondern lebte von den Erträgen
seines ererbten Vermögens, das später auch dem Sohn ein Leben ohne
finanzielle Zwänge ermöglichen sollte. Er war vielseitig interessiert
und gebildet, jedoch auch streng und pedantisch, was wiederholt zu
Konflikten in der Familie führte.

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1947)
	at controller.LineBreakOperation.execute(LineBreakOperation.java:106)
	at model.Algorithm.execute(Algorithm.java:100)
	at controller.Main.main(Main.java:86)
Java Result: 1
BUILD SUCCESSFUL (total time: 1 second)

**Comment by bombardellif** [comment]
Fixed
