### ISSUE TITLE
Profes- bug

### ISSUE THREAD

**Issue by wbombardellis** [bombardellif/acrostics-generator#5]
DonaldKnuth text
acrostic = knut

RUN RESULT:
Knuth ist der Sohn eines Lehrers. Er besuchte die Milwaukee Lutheran High School und begann sein Physikstudium am California Institute of Technology im September 1956. Aus zweierlei Gründen schlug er tatsächlich seinem zweiten Studienjahr jedoch den Weg zur Mathematik ein: Zum einen löste er ein Problem eines seiner Professoren der Mathematik, was ihm eine 1,0 als Note einbrachte, zum anderen fand er wenig Gefallen an den physikalischen Praktika. Er erhielt einen Bachelor- und einen Master-Abschluss 1960 an der Case Western Reserve University. 1963 erhielt er seinen Ph.D. vom California Institute of Technology bei Marshall Hall, wo er dann auch nach der Promotion Assistant Professor und 1966 Associate Professor und schließlich Professor wurde. 1968 wurde er Professor für Informatik an der Stanford University. Ab 1977 war er dort Fletcher Jones Profes- sor of Computer Science und ab 1990 Professor of the Art of Computer Programming. Seit 1993 ist er Professor Emeritus.Knuth ist der Sohn eines Lehrers.
Er besuchte die Milwaukee Lutheran High School und begann sein
Physikstudium am California Institute of Technology im September 1956.
Aus zweierlei Gründen schlug er tatsächlich seinem zweiten Studienjahr
jedoch den Weg zur Mathematik ein: Zum einen löste er ein Problem
eines seiner Professoren der Mathematik, was ihm eine 1,0 als Note
einbrachte, zum anderen fand er wenig Gefallen an den physikalischen
Praktika. Er erhielt einen Bachelor- und einen Master-Abschluss 1960
an der Case Western Reserve University. 1963 erhielt er seinen Ph.D.
vom California Institute of Technology bei Marshall Hall, wo er dann
auch nach der Promotion Assistant Professor und 1966 Associate
Professor und schließlich Professor wurde. 1968 wurde er Professor für
Informatik an der Stanford University. Ab 1977 war er dort Fletcher
Jones Profes- sor of Computer Science und ab 1990 Professor of the Art
of Computer Programming. Seit 1993 ist er Professor Emeritus.

Knuth ist der Sohn eines Lehrers. Er besuchte die Milwaukee Lutheran
High School und begann sein Physikstudium am California Institute of
Technology im September 1956.
Aus zweierlei Gründen schlug er tatsächlich seinem zweiten
Studienjahr jedoch den Weg zur Mathematik ein: Zum einen löste er ein
Problem eines seiner Professoren der Mathematik, was ihm eine 1,0 als
Note einbrachte, zum anderen fand er wenig Gefallen an den
physikalischen Praktika. Er erhielt einen Bachelor- und einen
Master-Abschluss 1960 an der Case Western Reserve University. 1963
erhielt er seinen Ph.D. vom California Institute of Technology bei
Marshall Hall, wo er dann auch nach der Promotion Assistant Professor
und 1966 Associate Professor und schließlich Professor wurde. 1968
wurde er Professor für Informatik an der Stanford University. Ab 1977
war er dort Fletcher Jones Profes- sor of Computer Science und ab 1990
Professor of the Art of Computer Programming. Seit 1993 ist er
Professor Emeritus.

Knuth ist der Sohn eines Lehrers. Er besuchte die Milwaukee Lutheran
High School und begann sein Physikstudium am California Institute of
Technology im September 1956. Aus zweierlei Gründen schlug er
tatsächlich seinem zweiten Studienjahr jedoch den Weg zur Mathematik
ein:
Zum einen löste er ein Problem eines seiner Professoren der
Mathematik, was ihm eine 1,0 als Note einbrachte, zum anderen fand er
wenig Gefallen an den physikalischen Praktika. Er erhielt einen
Bachelor- und einen Master-Abschluss 1960 an der Case Western Reserve
University. 1963 erhielt er seinen Ph.D. vom California Institute of
Technology bei Marshall Hall, wo er dann auch nach der Promotion
Assistant Professor und 1966 Associate Professor und schließlich
Professor wurde. 1968 wurde er Professor für Informatik an der
Stanford University. Ab 1977 war er dort Fletcher Jones Profes- sor of
Computer Science und ab 1990 Professor of the Art of Computer
Programming. Seit 1993 ist er Professor Emeritus.

Knuth ist der Sohn eines Lehrers. Er besuchte die Milwaukee Lutheran
High School und begann sein Physikstudium am California Institute of
Technology im September 1956. Aus zweierlei Gründen schlug er
tatsächlich seinem zweiten Studienjahr jedoch den Weg zur Mathematik
ein: Zum einen löste er ein Problem eines seiner Professoren der
Mathematik, was ihm eine 1,0 als Note einbrachte, zum anderen fand er
wenig Gefallen an den physikalischen Praktika.
Er erhielt einen Bachelor- und einen Master-Abschluss 1960 an der
Case Western Reserve University. 1963 erhielt er seinen Ph.D. vom
California Institute of Technology bei Marshall Hall, wo er dann auch
nach der Promotion Assistant Professor und 1966 Associate Professor
und schließlich Professor wurde. 1968 wurde er Professor für
Informatik an der Stanford University. Ab 1977 war er dort Fletcher
Jones Profes- sor of Computer Science und ab 1990 Professor of the Art
of Computer Programming. Seit 1993 ist er Professor Emeritus.

Knuth ist der Sohn eines Lehrers. Er besuchte die Milwaukee Lutheran
High School und begann sein Physikstudium am California Institute of
Technology im September 1956. Aus zweierlei Gründen schlug er
tatsächlich seinem zweiten Studienjahr jedoch den Weg zur Mathematik
ein: Zum einen löste er ein Problem eines seiner Professoren der
Mathematik, was ihm eine 1,0 als Note einbrachte, zum anderen fand er
wenig Gefallen an den physikalischen Praktika. Er erhielt einen
Bachelor- und einen Master-Abschluss 1960 an der Case Western Reserve
University.
1963 erhielt er seinen Ph.D. vom California Institute of Technology
bei Marshall Hall, wo er dann auch nach der Promotion Assistant
Professor und 1966 Associate Professor und schließlich Professor
wurde. 1968 wurde er Professor für Informatik an der Stanford
University. Ab 1977 war er dort Fletcher Jones Profes- sor of Computer
Science und ab 1990 Professor of the Art of Computer Programming. Seit
1993 ist er Professor Emeritus.

**Comment by bombardellif** [comment]
ANOTHER EXAMPLE:
Friedrich wurde im Berliner Stadtschloss geboren und war der älteste
überlebende Sohn von insgesamt 14 Kindern König Friedrich Wilhelms I.
und dessen Gattin Sophie Dorothea, der ersten hochad- ligen Königin
des Fürstentums zu Hannover.

Tip: The problem is in the Line Break operation.
Probabbly when joinning the strings after breaking the line, the function is ignoring the fact that the there might be hyphenated words in the of of some line.

**Comment by bombardellif** [comment]
I took a deeper look in the code and fixed the problem in the line break.
Now it's generating less nonsense requests to NetspeakAPI, what must increase our result numbers.

Closing the issue :smile:
