### ISSUE TITLE
Bug Ensure Constraint Operation

### ISSUE THREAD

**Issue by wbombardellis** [bombardellif/acrostics-generator#7]
How To reproduce:
Run the complete algorithm with input text "Text/Nachrichten_1.txt" and acrostic "Intim".

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 24
	at java.lang.String.substring(String.java:1950)
	at controller.EnsureConstraintsOperation.execute(EnsureConstraintsOperation.java:38)

**Comment by juergen123** [comment]
Hi,

can someone explain how to set up the redis

What i did so far:

1. Download the redis.io database
2. Extract it to redis-2.8.19 folder
3. Compile with make
4. cd src
5. ./redis-server 
-------------------------------

6. changed to data folder (contains import.database.py, openthesaurus.tex)
7. copied the content of redis-2.8.19 to the data folder (here something went wrong)
8. python import.database.py

The following error appears

Traceback (most recent call last):
  File "import-database.py", line 3, in <module>
    import redis
ImportError: No module named redis


Perhaps you see what it wrong here.
Thank you for help
Jürgen

















--------------------------------------------
William Bombardelli da Silva <notifications@github.com> schrieb am Di, 6.1.2015:

 Betreff: [acrostics-generator] Bug Ensure Constraint Operation (#7)
 An: "bombardellif/acrostics-generator" <acrostics-generator@noreply.github.com>
 Datum: Dienstag, 6. Januar, 2015 00:12 Uhr
 
 How To reproduce:
 
 Run the complete algorithm with input text
 "Text/Nachrichten_1.txt" and acrostic
 "Intim".
 
 Exception in thread "main"
 java.lang.StringIndexOutOfBoundsException: String index out
 of range: 24
 
     at java.lang.String.substring(String.java:1950)
 
     at
 controller.EnsureConstraintsOperation.execute(EnsureConstraintsOperation.java:38)
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by bombardellif** [comment]
Of course,

At first, the step 7 doesn't exist. There's no need to copy these contents.

Second, you need this library installed (redis).

1. Install the application called *pip* (I think it works: *apt-get install
python-pip*)
2. run: *pip install redis*
3. Then run:

*python import.database.py <http://import.database.py>*
In case of problems, please let me know.

Regards,
Fernando.


--
*Fernando Bombardelli da Silva*
Tel.: +49 176 35705843

2015-01-07 19:21 GMT+01:00 juergen123 <notifications@github.com>:

**Comment by wbombardellis** [comment]
Fixed by $12fd32b916
